// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBj8aDR9Bp_Qa63BLWoR7XzZGDNIDYRw',
    appId: '1:526099174197:web:ecc3ce56bce30b9b3bb27c',
    messagingSenderId: '526099174197',
    projectId: 'planta-f9ecd',
    authDomain: 'planta-f9ecd.firebaseapp.com',
    storageBucket: 'planta-f9ecd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7ugAVJS_tMzM14aRU4UUPcqbJkUW1pE',
    appId: '1:526099174197:android:3515cc6dbe3290203bb27c',
    messagingSenderId: '526099174197',
    projectId: 'planta-f9ecd',
    storageBucket: 'planta-f9ecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1saxzvn2HPHdFTuZs3KA5w778huX-p9k',
    appId: '1:526099174197:ios:61488edf38ed12823bb27c',
    messagingSenderId: '526099174197',
    projectId: 'planta-f9ecd',
    storageBucket: 'planta-f9ecd.firebasestorage.app',
    iosClientId: '526099174197-ussj9h3ujbi3j6h0jalnroeceulpk7ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.flourish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1saxzvn2HPHdFTuZs3KA5w778huX-p9k',
    appId: '1:526099174197:ios:61488edf38ed12823bb27c',
    messagingSenderId: '526099174197',
    projectId: 'planta-f9ecd',
    storageBucket: 'planta-f9ecd.firebasestorage.app',
    iosClientId: '526099174197-ussj9h3ujbi3j6h0jalnroeceulpk7ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.flourish',
  );

}